import { Icon } from '../ui.jsx';
import { planUrl } from '../planning/navigation.js';
import { executionProgress } from '../domain.js';

export function PublicHome({ plans }) {
  return <div className="page public-home"><section className="public-intro"><p className="eyebrow">MONITORAMENTO INSTITUCIONAL</p><h1>Acompanhe os planos e seus resultados</h1><p>Explore os objetivos, as iniciativas e a execução das ações institucionais. A consulta aos planos publicados é aberta e não exige login.</p><a className="br-button primary" href="#/planejamentos">Consultar planos <Icon name="arrow" size={16} /></a></section><section className="public-plans" aria-labelledby="public-plans-title"><div className="section-heading"><div><h2 id="public-plans-title">Planos publicados</h2><p>Escolha um plano para conhecer sua estrutura e acompanhar a execução.</p></div><a className="text-button" href="#/planejamentos">Ver todos os planos <Icon name="arrow" size={14} /></a></div>{plans.length ? <div className="plan-grid">{plans.map((plan) => { const progress = executionProgress({ actions: plan.items.flatMap((item) => item.actions) }); return <article className="br-card public-plan-card" key={plan.id}><div className="card-content"><div className="public-plan-identity"><span className={`plan-icon ${plan.type.toLowerCase()}`} aria-hidden="true"><Icon name={plan.type === 'PLS' ? 'leaf' : 'book'} size={24} /></span><span>{plan.start}–{plan.end}</span></div><h3><a href={`#${planUrl(plan.id)}`}>{plan.shortName}</a></h3><p>{plan.name}</p><dl className="public-plan-facts"><div><dt>Eixos temáticos</dt><dd>{plan.axes.length}</dd></div><div><dt>Execução das etapas</dt><dd>{progress.total ? `${progress.percent}%` : 'Sem dados'}</dd></div></dl>{!!progress.total && <p className="hint">{progress.done} de {progress.total} etapas ativas concluídas</p>}</div><div className="card-footer"><a className="br-button tertiary" href={`#${planUrl(plan.id)}`}>Consultar {plan.shortName} <Icon name="arrow" size={16} /></a></div></article>; })}</div> : <div className="br-message info"><div className="content"><strong>Nenhum plano publicado no momento.</strong><p>Os planos aparecerão aqui quando estiverem disponíveis para consulta.</p></div></div>}</section><section className="public-orientation" aria-labelledby="public-guide-title"><h2 id="public-guide-title">Como acompanhar</h2><div><article><Icon name="book" size={22} /><h3>Escolha o plano</h3><p>Consulte a vigência e os eixos temáticos que organizam o planejamento.</p></article><article><Icon name="layers" size={22} /><h3>Explore os objetivos</h3><p>Veja as iniciativas, os indicadores e as metas de cada eixo.</p></article><article><Icon name="chart" size={22} /><h3>Acompanhe a execução</h3><p>Consulte as ações e etapas. Seus percentuais de execução são apresentados separadamente dos resultados dos indicadores.</p></article></div></section></div>;
}

const content = {
  '/sobre': {
    title: 'Sobre o SUMI',
    lead: 'O Sistema Unificado de Monitoramento Institucional (SUMI) permite acompanhar os compromissos do planejamento institucional e os resultados alcançados ao longo do tempo. A plataforma reúne informações para a comunidade acadêmica, os gestores e a sociedade.',
    sections: [
      ['Desenvolvimento institucional', 'O Plano de Desenvolvimento Institucional (PDI) estabelece os objetivos e as prioridades que orientam a atuação da instituição durante sua vigência. Abrange temas como ensino, pesquisa, extensão, assistência estudantil, internacionalização, infraestrutura, gestão de pessoas e governança. Seu acompanhamento ajuda a compreender como essas prioridades se traduzem em ações e resultados.'],
      ['Sustentabilidade na gestão', 'O Plano Diretor de Logística Sustentável (PLS) orienta iniciativas para o uso responsável dos recursos e a melhoria das práticas de gestão. Entre seus temas estão o consumo consciente, as compras e contratações sustentáveis, a redução de impactos ambientais e a qualidade de vida. O acompanhamento dessas iniciativas permite conhecer os compromissos de sustentabilidade e sua evolução.'],
      ['Transparência e acesso à informação', 'A consulta aos planos publicados é aberta a todas as pessoas. Estudantes, servidores e demais interessados podem conhecer as prioridades institucionais, as metas estabelecidas e o andamento do trabalho. Esse acesso contribui para o debate sobre o desenvolvimento da instituição e aproxima a comunidade de seus compromissos e resultados.'],
      ['Acompanhamento ao longo do tempo', 'As informações de acompanhamento são registradas pelas unidades responsáveis pela execução dos planos. Metas e indicadores permitem observar os resultados em cada período, enquanto o andamento das ações mostra as entregas concluídas e o trabalho em curso. Essa visão ajuda a identificar avanços e aspectos que ainda precisam de atenção.'],
    ],
  },
  '/ajuda': { title: 'Ajuda e acessibilidade', lead: 'Orientações para consultar os planos e navegar no SUMI.', sections: [['Encontrar um plano', 'Abra Planos e filtre pelo tipo ou pelo nome. No PDI, escolha um eixo para consultar seus objetivos e iniciativas. Use o caminho de navegação no início da página para retornar aos níveis anteriores.'], ['Entender os resultados', 'Execução das etapas indica a proporção de etapas ativas concluídas. O resultado de um indicador é comparado à meta do período selecionado. Esses valores medem coisas diferentes. Ausência de resultado não significa resultado zero.'], ['Usar o teclado', 'Use Tab e Shift + Tab para percorrer os controles, Enter para ativar links e botões e Escape para fechar menus e janelas. Os primeiros links da página permitem ir diretamente ao conteúdo e ao rodapé.'], ['Recursos de acessibilidade', 'O controle Acessibilidade, no cabeçalho, permite escolher o tema claro ou escuro, alternar o alto contraste e ativar ou desativar o tradutor de Libras. O tema escuro e o alto contraste são alternativas de aparência. Quando ativado, o widget de Libras disponibiliza os controles de tradução.'], ['Acessar a área de trabalho', 'A consulta pública não exige login. Para atualizar ou validar informações, entre com seu acesso ao SUMI. Se precisar de credenciais ou permissões, procure a equipe responsável pela administração do seu acesso.']] },
  '/privacidade': { title: 'Informações sobre privacidade', lead: 'Conheça os recursos de armazenamento utilizados pelo SUMI durante a navegação.', sections: [['Consulta aos planos', 'A consulta pública não exige identificação nem criação de conta. Planos e informações internas dependem de acesso autorizado.'], ['Sessão de acesso', 'Ao entrar na área de trabalho, o sistema utiliza um cookie para manter sua sessão. O comando Sair encerra essa sessão.'], ['Preferências de acessibilidade', 'As preferências de tema, contraste e de exibição do tradutor de Libras são guardadas no navegador. Não é necessário entrar para utilizá-las.'], ['Tradução em Libras', 'Quando o tradutor está ativado, o navegador carrega o serviço VLibras. Você pode desativar sua exibição pelo controle Acessibilidade no cabeçalho.']] },
};

export function InformationPage({ path }) {
  const page = content[path];
  return <div className="page information-page"><div className="page-heading"><div><h1>{page.title}</h1><p>{page.lead}</p></div></div>{page.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}<a className="br-button secondary" href="#/planejamentos">Consultar planos <Icon name="arrow" size={16} /></a></div>;
}
